name: My Workflow
on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'My Input'
        default: 'uat'
        required: true
        type: choice
        options:
          - uat - pr
          - prod
jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'uat' }}
    steps:
      - name: Run my command
        run: |
          echo "${{ github.event.inputs.my_input }}"
